trading:
  symbol: "BTC/USDT"
  max_daily_trades: 10
  emergency_stop_loss: 0.15
  position_size: 0.05
  min_profit_threshold: 0.002
  max_position_size: 0.1
  max_margin_usage: 0.8
  max_position_exposure: 0.3
  max_daily_drawdown: 0.05
  max_volatility: 0.03
  atr_stop_loss_multiplier: 2.0
  atr_take_profit_multiplier: 3.0

indicators:
  rsi_period: 14
  rsi_overbought: 70
  rsi_oversold: 30
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  atr_period: 14
  bb_period: 20
  bb_std: 2
  stoch_k_period: 14
  stoch_d_period: 3
  ichimoku_tenkan: 9
  ichimoku_kijun: 26
  ichimoku_senkou_b: 52

risk:
  max_concurrent_trades: 3
  max_correlation: 0.7
  min_risk_reward_ratio: 2.0
  max_slippage: 0.001
  position_sizing_method: "kelly"
  kelly_fraction: 0.5
  optimal_f_risk: 0.02

model:
  model_path: "models/"
  training_data_path: "data/training_data.csv"
  prediction_threshold: 0.7
  retrain_interval: 24
  min_training_samples: 1000
  feature_importance_threshold: 0.01

monitor:
  metrics_update_interval: 60
  alert_thresholds:
    drawdown: 0.05
    win_rate: 0.4
    profit_factor: 1.5
    sharpe_ratio: 1.0
  performance_window: 30

api:
  binance_api_key: "${BINANCE_API_KEY}"
  binance_api_secret: "${BINANCE_API_SECRET}"
  telegram_bot_token: "${TELEGRAM_BOT_TOKEN}"
  telegram_chat_id: "${TELEGRAM_CHAT_ID}"

database:
  trades_db: "trades.db"
  logs_db: "trading_logs.db" 